### ISSUE TITLE
Battery has stopped reporting to Lilygo

### ISSUE THREAD

**Issue by mondc95ba** [dalathegreat/Battery-Emulator#139]
Hi Dala,

Apologies if this is the wrong forum to raise this issue but I have a AZE0 24kwh leaf battery and lilygo working and reporting to the fronius inverter.

I've been waiting for my installer to complete the upgrade to the gen24 plus from his end, so the battery hasn't been charging or discharging. Currently using the manual pre-charge, contactor method until the SSR arrive.

As of recent the lilygo is throwing error code 7, no matter the restart sequence. Do you know if this is an issue with the battery going into a sleep mode due to not seeing any discharge/charge for a week whilst being on and communicating?

I have also measured resistance when the 12v is off and the lilygo unpowered and it reads 60 ohm.

Edit:
Have opened the pack up and provided power, ground and connected to CAN direct and problem persist. Using a Link LX OBD2 reader and leafpsy yielded a CANBUS error and wouldn't connect either.
May actually be a dead LBC, will source a replacement and see if the problem persists.

Noting I had a car charger hooked up to a motorcycle battery which may have overcharged the little battery and in turn over volted the LBC.

**Comment by mondc95ba** [comment]
![Screenshot_20240115_212159_Chrome](https://github.com/dalathegreat/Battery-Emulator/assets/38099284/daca0c33-aa33-499f-aaef-6a360d68ea05)
![Screenshot_20240121_234130_Chrome](https://github.com/dalathegreat/Battery-Emulator/assets/38099284/b08e463a-3b63-46cc-8c2e-999591e72902)

**Comment by Cabooman** [comment]
I would suggest you power just the BMS and hook up your choice of CAN dongle as a first step. Current draw at ~12.7 V should be around 0.30-ish Ampere if I remember correctly. If you don't see any current draw or chatter on the CAN bus, you might have an LBC issue as you say

**Comment by dalathegreat** [comment]
I see you have a post on the diyelectriccar.com forum going, and extensive battery surgery ongoing aswell. I think it is best to continue discussion there, instead of the issue tracker for Battery-Emulator. Closing this issue!
