### ISSUE TITLE
Settings page added, Battery settings can be edited on the fly!

### ISSUE THREAD

**Issue by BEMSman** [dalathegreat/Battery-Emulator#141]
Not sure if it is intended or not?
Yes it is possible to change settings on the fly however upon reboot setting return to original coded values.
I don't see it as an issue, more as being useful for testing settings without recompiling and then once happy with settings, commit and recompile.

BTW great work

**Comment by dalathegreat** [comment]
@BEMSman This has now been added, Pull request here! https://github.com/dalathegreat/Battery-Emulator/pull/146
