### ISSUE TITLE
Tesla battery SOH 0% 

### ISSUE THREAD

**Issue by MarkoBolt** [dalathegreat/Battery-Emulator#144]
With version 4.4.0 I have a SOH of 0%. Versions up to 4.3.0 We did not have this issue. It was hardcoded. But Is the current SOH correct?

**Comment by dalathegreat** [comment]
I have made a fix for this in https://github.com/dalathegreat/Battery-Emulator/commit/56be5f83496a39ea56bec68c6d05670e18faf82f

The SOH% is now set to 99% incase the value is unavailable. And if the value is unavailable, the USB debug message is not as threatening :) Seems like many users have Tesla packs that has this Wh number unavailable, so hopefully this fix helps a bit!
