### ISSUE TITLE
Pylontech Force H2 as Battery

### ISSUE THREAD

**Issue by nils-ossenbrink** [dalathegreat/Battery-Emulator#161]
Hi,

I would like to use the battery mentioned above with my Fronius GEN24 (I bought it together with a GoodWe inverter before I found this nice project :-( )
Any hints where I can find some more detailed documentation about the can-protocol (in addition to PYLON-CAN.h/cpp)? 

Thanks!

Cheers
Nils

**Comment by dalathegreat** [comment]
Hi @nils-ossenbrink 
DBC file available here for Pylon protocol: https://www.eevblog.com/forum/programming/pylontech-sc0500-protocol-hacking/

**Comment by flo-tschi** [comment]
Hello Nils!

Did you had any success? I would also need this implementation because I want to connect my diybmsv4 to my fronius inverter. 

best
Florian

**Comment by nils-ossenbrink** [comment]
Hi, unfortunatrly not. I started to implement but my time ressources are
limited :-( The pylontech is connected to a goodwe Inverter now and is
working quite well. My aim is to run it with the fronius but I currently
don't know when I will have time for this project...

flo-tschi ***@***.***> schrieb am So., 31. März 2024, 14:55:

**Comment by flo-tschi** [comment]
That’s too bad!

I will try what I can do - but actually it’s quite a long time since I last programmed anything.

**Comment by dalathegreat** [comment]
@nils-ossenbrink 
@flo-tschi 
This has been added to 5.8.dev now in PR https://github.com/dalathegreat/Battery-Emulator/pull/265

Closing this ticket as completed!
