### ISSUE TITLE
QUESTIONS

### ISSUE THREAD

**Issue by kochikame** [dalathegreat/Battery-Emulator#179]
Hi
regarding these defines
does anyone know how exactly the function of these features?
thx in advance

//#define CONTACTOR_CONTROL     //Enable this line to have pins 25,32,33 handle automatic precharge/contactor+/contactor- closing sequence
//#define PWM_CONTACTOR_CONTROL /
//#define SERIAL_LINK_RECEIVER  //Enable this line to receive battery data over RS485 pins from another Lilygo (This LilyGo interfaces with inverter)
//#define SERIAL_LINK_TRANSMITTER

**Comment by dalathegreat** [comment]
@kochikame 
Contactor control / PWM control is useful for LEAF batteries, see Automatic Control section for explanation of this feature: https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/wiki/Nissan-LEAF-battery#automatic-control- 

The Serial Link is for Dual Lilygo funcitonality: https://github.com/dalathegreat/Battery-Emulator/wiki/Double-LilyGo

**Comment by kochikame** [comment]
Thank you

**Comment by mondc95ba** [comment]
no circuit diagram for the SSR circuit, propose using the below if suitable?
![SSR_Circuit](https://github.com/dalathegreat/Battery-Emulator/assets/38099284/7aec0267-31db-4a7d-9770-09b130b621e5)

**Comment by dalathegreat** [comment]
Massive thanks @mondc95ba , added to the Wiki! https://github.com/dalathegreat/Battery-Emulator/wiki/Nissan-LEAF-battery#automatic-control-
