### ISSUE TITLE
Tableau Doesnt show Totals

### ISSUE THREAD

**Issue by Curioustolearn7** [dalathegreat/Battery-Emulator#181]
[GitHub.docx](https://github.com/dalathegreat/Battery-Emulator/files/14275060/GitHub.docx)
How do i Total the grand Total column to give me one number as now its showing individual totals.  

Thanks

**Comment by dalathegreat** [comment]
Please do not post random files as attachments, and give more clear bug reporting. Closing this issue as wont do
