### ISSUE TITLE
Web server always shows "Battery Idle" if Solax CAN protocol used

### ISSUE THREAD

**Issue by davidhgriffiths** [dalathegreat/Battery-Emulator#185]
The code at lines 59 to 65 of BYD-MODBUS.cpp which sets the value of bms_char_dis_status is not in SOLAX-CAN.cpp so the battery always shows as idle.  Copying it into SOLAX-CAN.cpp around line 150 solves the problem but perhaps this code should be in  NISSAN-LEAF-BATTERY.cpp anyway?

**Comment by dalathegreat** [comment]
This is fixed when https://github.com/dalathegreat/Battery-Emulator/pull/186 is merged!

**Comment by dalathegreat** [comment]
Fixed to release 5.3.0 !
