### ISSUE TITLE
Cell monitor html formatting

### ISSUE THREAD

**Issue by BEMSman** [dalathegreat/Battery-Emulator#192]
It would be great if it is possible to add function to be able to adjust the number of coulombs across the page to make it easier to know at a glance where an offending cell is:

For example Renault and Nissan have 8 cells per module, BMW, KIA and Hyundai have 12 cells per module.
so my thoughts are can you make a coulomb count adjustable of between 4 - 12

**Comment by dalathegreat** [comment]
Even better, Cabooman is working on graphs:
![bild](https://github.com/dalathegreat/Battery-Emulator/assets/26695010/96cfe37f-3105-4bb8-b7e5-302ec2fb1cd4)

**Comment by BEMSman** [comment]
That sounds even better, that graph I assume is one line each cell, thats good as you will see where the offending cell is at a glance.
I have played around with the settings and have managed to get 12 cells wide, however its hard coding.
![image](https://github.com/dalathegreat/Battery-Emulator/assets/75639810/f85fa1b5-ff49-4b72-8668-c9c68583fdcc)

**Comment by matvey83** [comment]
Graph is a great idea!   That's awesome.  But also if we know the cell arrangement in packs, we can also provide some kind of a visual that would help see how cell groups are arranged in modules.  For example, NCM model 3 batteries, it would be useful for user to know that cells are grouped into modules as 1-23, 24-48, 49-73, 74-96.   And on 108 cell LFP packs, they are grouped into 1-26, 27-54, 55-82, 83-108.   It would be helpful to see at a glance if the issue can be resolved by replacing one module or not.   For packs with more modules this would be even more helpful.

**Comment by dalathegreat** [comment]
Closing this as completed, cell graphs was implemented way back earlier this year!
