### ISSUE TITLE
Wrong temperature readings on tesla battery

### ISSUE THREAD

**Issue by Plasticas** [dalathegreat/Battery-Emulator#193]
Hi, 
connected to can bus on 1666969-00-D battery and got min temp 120C, max temp 130C. Garage was about 13C, guesing maybe the reading is off by factor of 10? Or my battery gives me bad readings?

**Comment by Plasticas** [comment]
I got these readings in serial debug, but will try to look into web server.

**Comment by Plasticas** [comment]
I did checked and saw that temp readings on webserver are fine, only in serial debuger it is multiplied by 10.

**Comment by dalathegreat** [comment]
Ok! Closing this as a non-issue then! :)
