### ISSUE TITLE
Add SerialLink to build Actions on commit and PR, etc

### ISSUE THREAD

**Issue by Cabooman** [dalathegreat/Battery-Emulator#196]
SERIAL_LINK_RECEIVER/TRANSMITTER is currently not built in any Github Action. To ensure proper function for new releases, these should be added

**Comment by dalathegreat** [comment]
Added in https://github.com/dalathegreat/Battery-Emulator/pull/195/commits/4cf741a32be7bf2f545d5e868dbafd11866f179d
