### ISSUE TITLE
more than one battery

### ISSUE THREAD

**Issue by Coolj1** [dalathegreat/Battery-Emulator#210]
hi, and thanks a lot for this fantastic work!
is it possible to connect more then one battery (bmw i3)?

**Comment by kharnt0x** [comment]
at the moment, I don't think so. one lilygo per battery.

**Comment by dalathegreat** [comment]
I have 2x BMW i3 batteries in my garage, this is something we will develop support for later!

**Comment by Coolj1** [comment]
ok thx

**Comment by Coolj1** [comment]
hi dalathegreat,
there are 4 bmw i3 94ah batteries in my garage and a solax x3 g4 inverter connected to 10kW solar-modules.
Is there a way to connect all together...?
Maybe for each battery and the solax a separat esp with can-bus and the data from the battery-esp's to the solax-esp with rs485?

**Comment by dalathegreat** [comment]
@Coolj1 Please start testing this branch with 2x batteries. Once we get 2x working, it will be easy to add more later!

**Comment by nagyrobi** [comment]
https://hackaday.com/2024/08/13/from-vehicle-to-grid-to-diy-home-powerwalls/

**Comment by Coolj1** [comment]
👍
great work!

**Comment by dalathegreat** [comment]
Closing this as completed! :partying_face:
