### ISSUE TITLE
Differentiation between multiple emulators in MQTT integration 

### ISSUE THREAD

**Issue by Newevg** [dalathegreat/Battery-Emulator#214]
Description:
The current implementation of the MQTT integration lacks differentiation between multiple devices, resulting in all incoming messages being treated uniformly. This makes it challenging to differentiate between messages from different devices.

**Comment by Cabooman** [comment]
Since Feb 14 or so the MQTT implementation has differentiation based on network hostname. Perhaps you were using a release without this addition?
41b6551

**Comment by Newevg** [comment]
all good, fixed
