### ISSUE TITLE
CAN sending breaks when inverters change baud rate

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/Battery-Emulator#225]
### Problem description
Some inverters (like Sungrow) like to switch between 250kbps and 500kbps at startup, to see what type of battery is connected to it. This is a huge problem for us, since it can put the CAN bus into a faulted state that never recovers.

### Suggested solution
From RPI pelle_c

```
Believe I got this fixed now in rpi-version. Had to do a number of checks, and if one of them didn't pass the can-interface is restarted ("releasing notifiers", interface down/up), after 1-5 seconds (random).
Check that sending message returns ok
In addition, following is done on interval:
Check if the interface is reported as up
Check that the tx_counter on tne interface isn't the same as it was 60 secs ago
```

**Comment by dalathegreat** [comment]
User @Newevg is piloting an attempted fix for this, two lines of code added to the `ESP32CAN.cpp` file;

```
ESP32Can.CANStop();
ESP32Can.CANInit(); 
```

![bild](https://github.com/dalathegreat/Battery-Emulator/assets/26695010/bc30229e-1083-4971-a982-e21c2342b280)

Let's see if it helps anything long term!

**Comment by dalathegreat** [comment]
@Newevg , did this help?

**Comment by Newevg** [comment]
Good morning,Yes, I believe it helped as so far I haven’t had any issues Thank you 🙏 Sent from my iPhoneOn 11 Apr 2024, at 2:59 AM, Daniel Öster ***@***.***> wrote:﻿
@Newevg , did this help?
