### ISSUE TITLE
Feature request: Batteries in parallel

### ISSUE THREAD

**Issue by eham365** [dalathegreat/Battery-Emulator#227]
It would be nice to run several batteries in parallel, especially the 24 kWh Leaf. Maybe a Master - Slave configuration on the LilyGo.

**Comment by dalathegreat** [comment]
Pull request is up for the first Double Battery implementation: https://github.com/dalathegreat/Battery-Emulator/pull/261

**Comment by MartinVerges** [comment]
I would love to see that merged! Awesome feature

**Comment by nagyrobi** [comment]
It's in! https://hackaday.com/2024/08/13/from-vehicle-to-grid-to-diy-home-powerwalls/
