### ISSUE TITLE
Solax X3 Ultra compatibility?

### ISSUE THREAD

**Issue by freddanastrom** [dalathegreat/Battery-Emulator#232]
First of all, I've been following this project for a while. Great job with this!

I'm planning to replace my current non hybrid inverter with the new Solax X3 Ultra 25K.
X3 Ultra is specified to only be compatible with Solax batteries T-BAT H 5.8, T-BAT-SYS-HV-S 2.5 and 3.6

Would there be any chance that the current Solax code is emulating any of this batteries, so that the Ultra can use the same emulation?

If not. Would it be possible to emulate any of the compatible batteries, or are there something obvious that makes it impossible?
What can I do to support this development once I have the inverter in place?

**Comment by StarkJohan** [comment]
We just don't know until someone has tested the Ultra and/or dumped some logs with compatible battery systems.

**Comment by ilia92** [comment]
@freddanastrom have you bought the Inverter ? Did you start it ?

**Comment by freddanastrom** [comment]
> @freddanastrom have you bought the Inverter ? Did you start it ?

Yes, have the inverter since a few weeks. But I'm still waiting for my electrician to install it, which will probably be a few more weeks until it can be done.
I also bought a small stack of batteries (T-BAT-SYS-HV-S36) for testing.

CAN communication is however new to me, never worked with it before.
So any guidance to how I can start logging the communication between the inverter and battery would be appreciated.

**Comment by StarkJohan** [comment]
Do you happen to live in the southern parts of Sweden? 

The easiest way to get help with any parts of this project is joining the discord server. It's not free, but to me it's been essential in getting my system up and running. The time I've saved alone is worth the fee.

**Comment by josiahhiggs** [comment]
> No, I live near Nyköping. so a bit of a distance to the southern parts.. I wasn't familiar with the memberships and Discord server,but will check it out and maybe give it a go.

I would highly recommend joining the Discord server! And the Emulator should work on the Ultra, Solax Triple Power LFP CAN.

**Comment by DeadmaroZ-TLOTL** [comment]
With ultra inverter one problem, in main screen not show battery percentage, olways show 0%
![IMG_20240704_164221](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/01eb88fc-d035-45d9-b319-f636a10dc4c9)

![IMG_20240704_164215](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/eb4d6222-e471-4e44-aad6-54ddd8daff13)

![IMG_20240704_164050](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/073e90c3-ae2e-4ec9-ba50-f2fb91cf63a8)
![IMG_20240704_164124](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/ee6a0e57-e5f0-46a7-a32f-d4131bab8bdd)
!
![IMG_20240704_163931](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/e4bb2b9a-8df6-4ff2-8f7c-f4c4263d6111)

![IMG_20240704_163927](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/6f5cb714-0005-4d29-831c-8af4eaf36089)
[IMG_20240704_163827](https://github.com/dalathegreat/Battery-Emulator
![IMG_20240704_163922](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/1d3bffe3-1fda-4715-8d08-ee61d4b94c3a)

![IMG_20240704_163857](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/34981685-6f0e-46d9-98be-0b0345d01db2)
/assets/150045808/bdcb0213-abf3-4022-ab34-51193a1cf730)
![IMG_20240704_163850](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/75250c4a-c1dd-4aec-b17e-d0b5f301206a)

**Comment by DeadmaroZ-TLOTL** [comment]
With ultra inverter one problem, in main screen not show battery percentage, olways show 0%
![Uploading IMG_20240704_164221.jpg…]()

**Comment by DeadmaroZ-TLOTL** [comment]
With ultra inverter one problem, in main screen not show battery percentage, olways show 0%

![IMG_20240704_164221](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/8da57511-17e1-46a8-a793-7fd2f5deeaea)
![IMG_20240704_164215](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/b3c01fab-0d3a-42cf-a316-fdbbcd36a970)
![IMG_20240704_164124](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/13dbc7f0-4248-4745-835c-0279d22c7b4d)
![IMG_20240704_164050](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/aa5e0ae8-9e9c-4beb-8135-5d1b1df8a040)
![IMG_20240704_163931](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/b1db7faa-efb3-43b0-bccf-0de334feb873)
![IMG_20240704_163927](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/a98c34f7-d422-41d2-8403-77ab90170732)
![IMG_20240704_163922](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/58d0fe4a-01d3-4bf4-9d64-1eec5cff99cd)
![IMG_20240704_163857](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/d494b716-6c89-455c-be52-ccf44972d18f)
![IMG_20240704_163850](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/bc6cab8e-2614-4420-a563-9f2e2bd370a8)
![IMG_20240704_163827](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/4fb76e09-a99f-4291-af75-e75f0acb3873)

**Comment by DeadmaroZ-TLOTL** [comment]
Yes, basically the only problem at the moment is the SOC (State of Charge) on the main screen!

Yes, I am using the dual Lilygo variant!

I didn't quite understand about the modbus?

Which CAN dump do you need?

**Comment by StarkJohan** [comment]
Sounds very promising. 

I wonder if you are able to control the settings over modbus from e.g. Home Assistant? The existing integration should work but I'm just curious if it does. That way you can also force charge/discharge to check the battery function fully.

A CAN dump between the original battery and the inverter should give us all we need to get that last SOC sorted. The SOC likely just needs to go in an additional register for the Ultra compared to the inverters currently in use with the emulator.

**Comment by DeadmaroZ-TLOTL** [comment]
Under these conditions, something doesn't quite work anymore? These pictures and videos are from the X3-Hybrid-G1/G2. Later, I'll also make some from the X3-Ultra.

https://photos.app.goo.gl/hDpPAeptM84SikHw9

[CAN_Log_X3-Hybrid-G1G2.txt](https://github.com/user-attachments/files/16123352/CAN_Log_X3-Hybrid-G1G2.txt)
![IMG_20240708_085616](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/39fabc37-a7cc-4029-8336-2b2f9220c9ae)
![IMG_20240708_085624](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/a9103dd3-78e3-4d77-8d3a-7025f3883185)
![IMG_20240708_085818](https://github.com/dalathegreat/Battery-Emulator/assets/150045808/4ec7250f-cbd7-4a10-9d37-3ddc566c209a)

**Comment by DeadmaroZ-TLOTL** [comment]
[CAN_Log_X3-Ultra.txt](https://github.com/user-attachments/files/16123484/CAN_Log_X3-Ultra.txt)

**Comment by DeadmaroZ-TLOTL** [comment]
Solax ultra log with Triple battery s7 https://f6340f99acf1.sn.mynetname.net:8099/index.php/s/fSeSw77aGCQ8Skr

Battery 2 is solax battery, battery 1 is tesla battery!

**Comment by DeadmaroZ-TLOTL** [comment]
What else is needed to fully integrate the Solax Ultra?

**Comment by dalathegreat** [comment]
Fix is now up as a PR, to get the SOC% to work in the app when using a Solax Ultra! https://github.com/dalathegreat/Battery-Emulator/pull/656

**Comment by dalathegreat** [comment]
Closing this as completed. **Solax Ultra works perfectly** now with the addition of PR #704
