### ISSUE TITLE
 Feature request : Add support for Volkswagen MEB BMS

### ISSUE THREAD

**Issue by nkrepo** [dalathegreat/Battery-Emulator#242]
Hi all,
First to say that is a great project and congrats to all of you!
I would like to ask if there are plans to support Volkswagen MEB BMS ? I know probably is hard to get hold of a complete VW MEB battery and they are way more expensive than alternatives, but I assume in the feature they will be more readily available.

I noticed that there is work from @Tom-evnut  implementing the decoding of the BMS  from CAN [VW BMS](https://github.com/Tom-evnut/VW-bms). Is there any way to integrate it to Battery-Emulator ?

**Comment by Tom-evnut** [comment]
This is the internal CAN bus of the battery not the external one you would need.

**Comment by nkrepo** [comment]
Oh that's unfortunate, lets hope in the feature there will be documentation how to access the main BMS controller for the MEB batteries. Thank you for the quick reply !

**Comment by nkrepo** [comment]
One question , related with the possibility of getting support for MEB platform BMS. The main BMS controller for MEB platform is on the battery pack or it is integrated with the rest of the car electronics ?

**Comment by zeman51** [comment]
Hello. It is integrated into battery module.

**Comment by dalathegreat** [comment]
See https://github.com/dalathegreat/Battery-Emulator/wiki/Data-needed-for-new-battery-integration

**Comment by mvgalen** [comment]
If I understand correctly, this issue was related to adding support for the complete MEB batteries. Initial support has been merged. So, I am closing this issue.

**Comment by nkrepo** [comment]
> If I understand correctly, this issue was related to adding support for the complete MEB batteries. Initial support has been merged. So, I am closing this issue.

Yes it is about complete MEB batteries, thank you for your contribution.
