### ISSUE TITLE
Wrong PYLON 30kW Leaf capacity 

### ISSUE THREAD

**Issue by gkasprow** [dalathegreat/Battery-Emulator#285]
The battery capacity shown in SOFAR  HYD20KTL inverter is 86Ah, but the Leaf module I connected is 30kWh.
![2024-05-04 06 21 48](https://github.com/dalathegreat/Battery-Emulator/assets/4325054/eaf9e201-ff05-4d0f-b212-b441db645c0a)

**Comment by dalathegreat** [comment]
This was fixed 16 hours ago, in PR https://github.com/dalathegreat/Battery-Emulator/pull/284

Closing this one as resolved!
