### ISSUE TITLE
Option in User_settings to set name

### ISSUE THREAD

**Issue by eriksson25** [dalathegreat/Battery-Emulator#300]
Running several systems, and accessing them throe VPN to monitor them it would be awesome if we could set a system name that shows on webpage instead of "Battery Emulator" direct in the User settings file. It could have "Battery Emulator" as default and then it would be easy to change.

**Comment by dalathegreat** [comment]
@eriksson25 
Added this in PR https://github.com/dalathegreat/Battery-Emulator/pull/312

Now the ssidAP name set in USER_SETTINGS.cpp will also be shown as header (Default is Battery Emulator)

![bild](https://github.com/dalathegreat/Battery-Emulator/assets/26695010/5c5629f3-0f3d-43e5-9105-6be2bee74af7)

**Comment by eriksson25** [comment]
Awsome! Will test it out!

**Comment by dalathegreat** [comment]
Closing, others approved the PR!
