### ISSUE TITLE
can protocol not working

### ISSUE THREAD

**Issue by Abdelrahmanars91** [dalathegreat/Battery-Emulator#316]
im using the library  https://github.com/Xinyuan-LilyGO/T-CAN485 but data no appear on pcan pus view 
please answer me
abdalrhmanars91@gmail.com

**Comment by dalathegreat** [comment]
@Abdelrahmanars91 

Too little info.

What battery? What inverter? What error message?

**Comment by Abdelrahmanars91** [comment]
I used  PYLON_BATTERY
i work done
 but i want to display data of  voltage and current and capacity , please
how can i do this give me example code

**Comment by Abdelrahmanars91** [comment]
HI HOW ARE YOU
CAN YOU EXPLAIN BY VIDEO  HOW TO SUBSCRIBE MQTT AND SEND DATAD IN
THINGSBOARD
