### ISSUE TITLE
e-GMP show positive Amp/Volt + battery charging - when discharging

### ISSUE THREAD

**Issue by JorgenSeemann** [dalathegreat/Battery-Emulator#342]
![20240612_203239](https://github.com/dalathegreat/Battery-Emulator/assets/89704368/ad313158-4c3a-4c14-ba00-b606c7e849e6)
Here I'm pulling 2kw (boiling water) from batttery. I would expect negative Amp/Volt and battery discharge

**Comment by dalathegreat** [comment]
This is fixed in 6.3.dev main now!
