### ISSUE TITLE
Integration SAFT Batterie

### ISSUE THREAD

**Issue by SN00CS** [dalathegreat/Battery-Emulator#348]
Hi,
we are about 20 persons, who have an early ESS, which has a SAFT Lithium-Ion Battery System with 10 Synerion Moduls (max. 560V 25kWh) inside. A similar system is build in a BOSCH ESS, but with only max. 6 Moduls. 
Is there anybody, who can program/integrate the battery in this project? There is no revers engineering needed, because the whole CAN registry is known. Hope someone can help us to integrate it to Battery-Emulator.

**Comment by dalathegreat** [comment]
Hi @SN00CS 
I can code in support for this battery type, please email me (check my profile) and we can take it from there!

**Comment by dalathegreat** [comment]
Turns out the document is a CANopen document, not something that easily integrates with this project unfortunately :/

**Comment by dalathegreat** [comment]
Closing as wont do at the moment, due to no CANopen implementation exists
