### ISSUE TITLE
Work with Model 3: RWD - China manufactured pack - LFP cells - Part number 1567439-00-C

### ISSUE THREAD

**Issue by DeadmaroZ-TLOTL** [dalathegreat/Battery-Emulator#351]
Work with Model 3: RWD - China manufactured pack - LFP cells - Part number 1567439-00-C

**Comment by dalathegreat** [comment]
Thanks, This was already in the Wiki I see! https://github.com/dalathegreat/Battery-Emulator/wiki/Tesla-Model-S-3-X-Y-battery
