### ISSUE TITLE
Webserver / Settings / Decimals not saved

### ISSUE THREAD

**Issue by GubbJVL** [dalathegreat/Battery-Emulator#380]
On webserver -> Settings.

Change any value (charge/discharge amp and min/max soc tested) to a value with decimals; the decimals don't save.

Presume issue is in webserver.cpp;

> String value = request->getParam("value")->value();
> datalayer.battery.settings.max_percentage = value.toInt() * 100;

the toInt makes it an integer before multiplying. Use float instead?

**Comment by dalathegreat** [comment]
Closing this issue as fixed, PR https://github.com/dalathegreat/Battery-Emulator/pull/386 solves this! :raised_hands:
