### ISSUE TITLE
Fronius Gen24 10KW 11Kwh BYD 

### ISSUE THREAD

**Issue by Mights001** [dalathegreat/Battery-Emulator#383]
Hello Guys, 

I have a BYD Battery and now want to expand it with another HV memory that communicates via Pylontech HV. Does that work with that? 
And how is the wiring and what do I need for it?

In the software I can only activate one Battery, it somehow works?

Thx. for reply

**Comment by dalathegreat** [comment]
Most likely this wont work. Please add a diagram of what you intend to connect, and we can say if it will work or not!

**Comment by Mights001** [comment]
Hello, here is a block diagram.
My first thought is to connect the two batteries together on the DC side, of course with the same voltage level.
The battery emulator should then query both batteries and pass them on to the Fronius via the BYD Modbus interface.

![grafik](https://github.com/user-attachments/assets/4f450ed9-5c80-4a88-bba1-e48503eeabb2)

**Comment by dalathegreat** [comment]
This is not supported, we have no way to add a BYD battery together with a Pylon battery unfortunately. But the software is open source, so you can attempt adding support for this specific combo!
