### ISSUE TITLE
Solax protocol does not respect user settings for charge/discharge

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/Battery-Emulator#385]
### What
The limits set in the Webserver are not applied on Solax CAN protocol. This should be added!

**Comment by mcdzim** [comment]
Having tested susbtantially with the Fox kh10 and 5kw versions they have rather inaccurate internal battery voltage measurements. 

As such when simulating charge data for them they don't really listen to the charge voltage limit and instead only listen to charge and discharge current limits. 

Might be worth noting that

**Comment by dalathegreat** [comment]
Closing this as fixed, will be included in next release (7.5.0)
