### ISSUE TITLE
Contractors don’t close although all conditions are met

### ISSUE THREAD

**Issue by RusVl** [dalathegreat/Battery-Emulator#390]
![2BCFDDDA-B9A8-43A7-99E6-93E2F66A5961](https://github.com/user-attachments/assets/2e76d14c-2b1c-48b6-b109-0d803a23ee33)
contactors do not close even with soldered jumpers. What  other options are there?

**Comment by dalathegreat** [comment]
Apart from HVIL, you need to have
- Pyrofuse mounted
- 60/120 Ohm resistor on X98 (depending on RWD / AWD)
- Capacitor on HV output
- PCS installed inside battery

See the wiki, for a detailed guide: https://github.com/dalathegreat/Battery-Emulator/wiki/Tesla-Model-S-3-X-Y-battery#example-integration

**Comment by RusVl** [comment]
![Uploading 31620E01-2DB8-4F19-8600-99AE62AED360.jpeg…]()

**Comment by RusVl** [comment]
I don’t have any idea!

**Comment by RusVl** [comment]
![4AFC5190-4D4E-4DD9-9E03-4DE66DC9A5FE](https://github.com/user-attachments/assets/a050a3f0-82c4-49a1-a273-fe2d56422fa2)
I made all options. Only used resistor 2 Om and jumper instead pyro fuse.
![3D42ABAC-5641-42A8-9FDF-C0F5BCCA68F5](https://github.com/user-attachments/assets/7650ea87-378a-46e7-a11d-eb34fd28b544)

**Comment by RusVl** [comment]
![99B35943-16FE-4633-BD9B-C5FD12A9A8C7](https://github.com/user-attachments/assets/fb2ea936-d27a-47a0-ad95-cfd016e540cd)

**Comment by RusVl** [comment]
May be I change bms of my battery in older bms?

**Comment by dalathegreat** [comment]
Your screenshot shows low voltage (12V battery) as 7V. Looks like the power supply is not stable enough?

**Comment by RusVl** [comment]
Дякую. Спробую іншу батарею.

**Comment by RusVl** [comment]
the problem was solved by replacing the 22-year-old BMS with the 21-year-old BMS.
thanks to everyone who responded.
