### ISSUE TITLE
Hyndai/kia 64kw

### ISSUE THREAD

**Issue by JKi92** [dalathegreat/Battery-Emulator#395]
Hei 
akku on toiminut 3 viikkoa.
Heräte akusta oli virta loppunut.vaihdoin akun bms lähti päälle ja heti sammui.
Nyt battery emulator näyttää akku tyhjä / alijännite. Mistä lähtisin vikaa etsimään?
![IMG_0594](https://github.com/user-attachments/assets/72619b59-783e-4441-a3b3-ce0954911cbd)
![IMG_0596](https://github.com/user-attachments/assets/20ef98d3-598a-466e-b23a-44737daccaa4)

**Comment by JKi92** [comment]
![IMG_0594](https://github.com/user-attachments/assets/0a0c7a6f-56d5-4397-98b0-3a2c1dbf27b8)

**Comment by dalathegreat** [comment]
Please use english to reach wider target audience.

Looks like CAN communication is entirely down. We have seen users with fried CAN chips, due to incorrect grounding. See CAN troubleshooting tips here: https://github.com/dalathegreat/Battery-Emulator/wiki#can-wiring-troubleshooting
