### ISSUE TITLE
Dual lilygo 

### ISSUE THREAD

**Issue by Alizainharoon** [dalathegreat/Battery-Emulator#401]
I have a question: If I have two batteries with different capacities, can I operate them, one primary and the other spare? 
Does Dual Lilygo do that? 
The battery simulator has the feature of running the ATS circuit within the program and selecting it from among the 
batteries automatically

**Comment by dalathegreat** [comment]
> I have a question: If I have two batteries with different capacities, can I operate them, one primary and the other spare?

Yes
> Does Dual Lilygo do that?

No, this requires either dual CAN or a Stark CMR board. See the Double Battery wiki https://github.com/dalathegreat/Battery-Emulator/wiki/Double-Battery
