### ISSUE TITLE
Arduino IDE 2.3. edit User Settings in /* Battery settings */

### ISSUE THREAD

**Issue by dvbhannes** [dalathegreat/Battery-Emulator#413]
I don't really understand what these parameters allow.
I have a Nissan Leaf battery with 30 kWh and a Fronius Gen24 10 plus to use
/* Battery settings */

// 300 = 30.0A , BYD CAN specific setting, Max charge in Amp (Some inverters needs to be limited)
#define BATTERY_MAX_CHARGE_AMP 300
// 300 = 30.0A , BYD CAN specific setting, Max discharge in Amp (Some inverters needs to be limited)
#define BATTERY_MAX_DISCHARGE_AMP 300

**Comment by dalathegreat** [comment]
This is explained in the wiki https://github.com/dalathegreat/Battery-Emulator/wiki/Webserver-guide#battery-chargedischarge-limit

**Comment by dvbhannes** [comment]
I still have a problem with the "contactor" so that the voltage can be measured at the HV connection so that I can be sure where plus and minus are. How do I switch the SSR 10 DD so that the Nissan Leaf battery supplies power? What else do I need to activate in the user settings options?
