### ISSUE TITLE
Add support for PSA/STELLANTIS e-CMP batteries (Peugeot/Opel/Jeep etc) - Help needed

### ISSUE THREAD

**Issue by albertofralbe** [dalathegreat/Battery-Emulator#414]
Hi there,
I have a 2021 Peugeot e-208 100kW and I would like to help the adoption of this platform's battery that is becoming increasingly common in Europe. How can I do this? 
I know that it has internal BMS using MAX17823 master and various slaves, one for each cells module.

https://openinverter.org/forum/viewtopic.php?t=2181

https://openinverter.org/forum/viewtopic.php?t=2465

https://openinverter.org/forum/viewtopic.php?t=2675

Btw just found a thread about this here: https://openinverter.org/forum/viewtopic.php?t=4612

**Comment by dalathegreat** [comment]
Hi @albertofralbe ,
See this page, we need CAN logs to get started: https://github.com/dalathegreat/Battery-Emulator/wiki/Data-needed-for-new-battery-integration

**Comment by opelpanfan** [comment]
In 2 weeks I'm going get delivered one of these batteries (corsa-e 2022) also personalu own citroen e-c4 (2023) so going to be doing investigations and can logging

**Comment by dalathegreat** [comment]
eCMP PR opened: https://github.com/dalathegreat/Battery-Emulator/pull/462

**Comment by opelpanfan** [comment]
Varies can logs and dbc file is located on my gdrive 
https://drive.google.com/drive/folders/1S-Nf0dN5nZi71HhXIoM3GTydEk_VHHuM

Latest discovery is shunt current readings (small part is missing to discover what way current goes)

**Comment by dalathegreat** [comment]
I merged PR #462 , we can continue with the Stellantis integration now in smaller bits!

**Comment by Angel-Perez-Lopez** [comment]
Has anybody tested this integration so far?
