### ISSUE TITLE
BMW i3: Some packs have other CRC check

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/Battery-Emulator#418]
### What
Some BMW i3 batteries do not pass the CRC check on incoming messages. This causes yellow light to be permanently on, and warning event.

Could be some versions of the BMW i3 SME that dont calculate CRC in the same way as others. We should add a check, if the first message is broken, skip even trying to use CRC

**Comment by ababians** [comment]
This situation appears in my case and regarding a 60Ah battery from November 2014

**Comment by dalathegreat** [comment]
Closing this, solved with #419 , next release included in is 7.1.0
