### ISSUE TITLE
Values required for a new battery implementation 

### ISSUE THREAD

**Issue by wrightwells** [dalathegreat/Battery-Emulator#422]
Just want to confirm the values required , where they are stored and their format passed into the datalayer etc

<!DOCTYPE html><head></head>
Value | Type | Source(s) | value|format | Comment
-- | -- | -- | -- | --| --
SOC | Mandatory | Battery | datalayer.battery.status.real_soc | 0000 |State Of Charge on dash in % State of charge.
DC voltage | Mandatory | Battery | datalayer.battery.status.voltage_dV | 0000|  Vbatt in units of mV (divide by 1000 to get Volts) Total HV battery DC voltage DC current | Mandatory | Battery | datalayer.battery.status.current_dA | 0000 |HV battery DC current Pack max temperature | Mandatory | Battery | datalayer.battery.status.temperature_max_dC |  |battery temp in celcius HV battery max measured temperature Pack min temperature | Mandatory | Battery | datalayer.battery.status.temperature_min_dC |  |HV battery min measured temperature Maximum pack DC voltage | Mandatory | Battery/Manual configuration | datalayer.battery.info.max_design_voltage_dV |  |The maximum allowed HV battery pack voltage
Minimum pack DC voltage | Mandatory | Battery/Manual configuration |datalayer.battery.info.min_design_voltage_dV |  |The minimum allowed HV battery pack voltage
Pack capacity | Mandatory | BatteryManual configuration | datalayer.battery.info.total_capacity_Wh or BATTERY_WH_MAX |  |Total HV battery pack capacity in kWh or similar
Remaining pack capacity | Mandatory | Battery/Manual configuration | datalayer.battery.status.remaining_capacity_Wh or ? ? |  |Remaining HV battery pack capacity in kWh or similar
Allowed charge power | Recommended | BatteryEstimation | datalayer.battery.status.max_charge_power_W or ? BATTERY_MAX_CHARGE_AMP? |  |The maximum allowed charge power of the HV battery. Preferably taken from battery communication, but can be estimated
Allowed discharge power | Recommended | BatteryEstimation | datalayer.battery.status.max_discharge_power_W ? BATTERY_MAX_DISCHARGE_AMP ? | |The minimum allowed charge power of the HV battery. Preferably taken from battery communication, but can be estimated
SOH | Optional | BatteryEstimationManual configuration | datalayer.battery.status.soh_pptt |  |State of health. Preferably taken from battery communication, but can be estimated
Cell voltages | Optional | Battery | (MISSING). |  |Voltages of individual cells in the pack. Good for extra layers of safety and for judging the overall health of the pack
Number of cells | Optional | BatteryManual configuration | datalayer.battery.info.number_of_cells |  |The total number of cells in the pack. Used for tracking min/max, displaying values in the web UI properly, etc
Pack chemistry type | Optional | BatteryManual configuration | (MISSING) |  |The chemistry leads to different

What about
Battery charge and discharge from user_settings.cpp

**Comment by dalathegreat** [comment]
The battery charge/discharge limits set in USER_SETTINGS is applied on top of the values sent by battery. See this wiki page for more info on them: https://github.com/dalathegreat/Battery-Emulator/wiki/Webserver-guide#battery-chargedischarge-limit

The format for each datatype in the datalayer can be seen in the file https://github.com/dalathegreat/Battery-Emulator/blob/main/Software/src/datalayer/datalayer.h
