### ISSUE TITLE
Relay Module GPIO Active High/Low Support

### ISSUE THREAD

**Issue by malcolmputer** [dalathegreat/Battery-Emulator#447]
I'm utilizing a 4 channel relay board that's got all of the features one might want (opto-isolated inputs, 5V relay control, and some status LEDs, readily 3D printed cases etc) except it's ACTIVE LOW!

Can we support re-mapping active LOW and active HIGH with a toggle somewhere (Maybe in User Settings next to the Contactor enabled flag?) for Contactors (HV+, HV-, HV-Pre) and BMS_Power?

For those who want to follow along, here's the 
Amazon link: https://www.amazon.com/JBtek-Channel-Module-Arduino-Raspberry/dp/B00KTEN3TM
Thingiverse Link for the Case: https://www.thingiverse.com/thing:2351293

**Comment by dalathegreat** [comment]
Closing as duplicate, included in 7.8.dev (Target 7.8.0)
