### ISSUE TITLE
Feature request: Clear events

### ISSUE THREAD

**Issue by JorgenSeemann** [dalathegreat/Battery-Emulator#485]
### Expected Behavior

When an error condition dissapears, the system should return to green
Alternative a way to clear error events and re-asses system

### Actual Behavior

When Solax+eE-MP is comming alive, it can take the solax so long time to get online that the lilygo goes into error.
It then stays yellow even when everything is working ok.

### Steps to Reproduce the Problem

1. Power up E-GMP, lilygo, MCP
1. Power up Solax
1. Sometimes it goes into yellow error, and webserver needs rebooting to get grean

### Settings

- Software version: 7.4.dev
- Battery used: E-GMP 73kWh
- Inverter communication protocol: CAN
- Hardware used for Battery-Emulator: `HW_LILYGO+MCP
- CONTACTOR_CONTROL: yes
- DUAL_CAN: no
- WEBSERVER: `yes`
- MQTT: `no`

**Comment by dalathegreat** [comment]
Fixed with the introduction of PR https://github.com/dalathegreat/Battery-Emulator/pull/487
Will be included in release 7.4.0
