### ISSUE TITLE
Is BMW iX3 80kWh battery supported?

### ISSUE THREAD

**Issue by JimsterCoder** [dalathegreat/Battery-Emulator#521]
I am looking for a battery for building a BESS.  Here in NZ supply of affordable damaged EVs is sparse but there has been a few BMW iX3.   I see the Battery-Emulator supports the i3, would this protocol work on an iX3 battery?  Any insight appreciated. Thanks.

**Comment by dalathegreat** [comment]
These batteries are NOT supported yet.
