### ISSUE TITLE
Battery not recognised by Fronius Gen24

### ISSUE THREAD

**Issue by GraphicObession** [dalathegreat/Battery-Emulator#529]
Hi 

Great Project, thanks Dala!

I am setting up a BYD ATT 3 battery and a Fronius Gen24 ( not the plus version, but I have purchased a licence to do the upgrade, however I am not 100% sure they have installed the correct licence) and I am having a few issues as listed below:

1 - The Emulator appears to be communicating with the battery however the cell information is not loading 
2 - The Fronius has not correctly discovered the battery and I am unable to find any battery settings.

I have not connected the HV yet, would this have any affect on the above issues?

Any help is appreciated.

- Software version: `7.4.1`
- Battery used: `BYD ATTO 3`
- Inverter communication protocol: `ModBus`
- Hardware used for Battery-Emulator: `HW_LILYGO`
- CONTACTOR_CONTROL: `no` not tested
- DUAL_CAN: `no`
- WEBSERVER: `yes`
- MQTT: `yes`

![Cells](https://github.com/user-attachments/assets/fdcb1796-3cb4-4c44-bec7-e0df4cad4df8)
![Emulator](https://github.com/user-attachments/assets/52e2d168-9dd6-42f6-b282-617ea995a85e)
![Inverter Screen](https://github.com/user-attachments/assets/c50834f9-ddbe-47dd-847c-7f4b75894edc)
![Licence](https://github.com/user-attachments/assets/6c14d96c-e97d-407f-bea5-0da27cf40084)
![Portal Message](https://github.com/user-attachments/assets/b9564724-0a90-4d1f-b853-698588bfac32)

**Comment by dalathegreat** [comment]
Hi,
- Yes, High voltage needs to be present on the Inverter for it to proceed with checking it.
- Fronius configuration is done via the "Solar.start" android application
- Contact Fronius if the + license is not applied.
- Cellmonitor view is not available for Byd Atto 3 yet. We only have min/max cellvoltage.

**Comment by GraphicObession** [comment]
Thanks Dala, I appreciate the info!

**Comment by GraphicObession** [comment]
My setup is working now. 

Thanks again Dala!
