### ISSUE TITLE
Info Request -BYD Atto 3 pack cut in half

### ISSUE THREAD

**Issue by deece** [dalathegreat/Battery-Emulator#533]
I'm hoping someone with experience can advise.

I'm going to use an Atto3 pack with my solar inverter.

The problem is my inverter has a max voltage of 400V, and the pack exceeds this. 

I'm thinking I could open the pack, and reconfigure the pack as 63S/2P, or whatever multiple of cells the BMSes supports.

Would the BMS modules support this, or would I need to go to an aftermarket BMS?

**Comment by dalathegreat** [comment]
There is currently no support for using half-packs. Every EV BMS go into error state if half the battery is missing. So you will need to add an aftermarket BMS.
