### ISSUE TITLE
Support for 48V batteries & inverters

### ISSUE THREAD

**Issue by M4GNV5** [dalathegreat/Battery-Emulator#536]
Hey,

I am currently looking into building an 48V system for solar storage.
I own a Renault Twizy, which comes with a 48~58V 6.6kWh NMC battery and thus fits into the voltage range of many of the low voltage hybrid inverters on the market today.

I currently see no support for any LV batteries/inverters in this project, however the software architecture looks generic enough to support both HV and LV. Would it be OK to send pull requests for different LV battery & inverter protocols?

Most LV inverters and batteries support the ["pylontech" CAN protocol](https://www.photovoltaikforum.com/core/attachment/77135-pylon-bms-protocol-can-can-20161103-pdf/) (originally used by US3000C/US5000C/... batteries), which offers good interoperability between different battery & inverter vendors. I would probably start with this one and the [Twizy CAN Bus](https://docs.google.com/spreadsheets/d/1gOrG9rnGR9YuMGakAbl4s97a6irHF6UNFV1TS5Ll7MY/edit?gid=0#gid=0).
Some LV inverters use proprietary protocols (Usually making the inverter cheaper and the batteries expensive). In the future someone could add some of those protocols as well.

As a general note: Some issues mention a discord server/channel? I have not yet found a link to that discord yet though. Maybe one could add this to the readme and/or wiki?

**Comment by dalathegreat** [comment]
Hi @M4GNV5 
Thanks for the Twizy PR! Yes we recently added support for DIY batteries via an aftermarket BMS. This has led to people adding lower voltage batteries (50S to 60S) with inverters that take lower voltages like 150VDC. So it's not entirely impossible to go with a 48V battery, we know the code works well already with low-ish voltage packs.

At the moment interest for low voltage has been quite **low** :sweat_smile: , but feel free to start development! We are not opposed to 48V architecture in any way.

The Discord server is available via the [Patreon](https://www.patreon.com/dala) page
