### ISSUE TITLE
Renault ZOE 52 kWh battery integration

### ISSUE THREAD

**Issue by pazdzierzz** [dalathegreat/Battery-Emulator#546]
### What

Integration of 52 kWh Renault ZOE battery. Phase 2 ZOE has completely different battery architecture, 1 master unit with 8 slaves instead of single BMS module. There is still only postive contactor with precharge.

### Stuff already gathered

1. **Small amount of battery log when using** CAN Z.E. OBD scanning app:

![image](https://github.com/user-attachments/assets/8d88607e-d154-4c0f-9c83-26b91db79445)

[zoe52_canZE.txt](https://github.com/user-attachments/files/17449457/zoe52_canZE.txt)

2. **LBC files from CAN ZE repo**: [https://github.com/fesch/CanZE/tree/master/app/src/main/assets/ZOE_Ph2](url)

3. **LOTS of useful info from ljames28 Github**: [https://github.com/ljames28/Renault-Zoe-PH2-ZE50-Canbus-LBC-Information?tab=readme-ov-file](url)

I have a car with/without battery available.

**Comment by dalathegreat** [comment]
Work started on https://github.com/dalathegreat/Battery-Emulator/tree/feature/zoe-ph2
