### ISSUE TITLE
Battery installation orientation 

### ISSUE THREAD

**Issue by laughingguffly** [dalathegreat/Battery-Emulator#549]
Maybe a dumb question. But I'm thinking of installing the entire EV  battery chassis  vertically on a wall. I presume that's fine and doesnt lead to any undesired load (weight) or overheating at the cells towards the bottom?

**Comment by nagyrobi** [comment]
Many people install it against a wall, but there's no long term experience with what happens if some chemicals spill from the cells at the top...

**Comment by havrla** [comment]
BMW I3 can be on the wall.

**Comment by dalathegreat** [comment]
Nissan LEAF manuals also OK wallmounting. Closing this question as resolved, answer is Yes :)

**Comment by nagyrobi** [comment]
Manuals?

**Comment by havrla** [comment]
Nothing is spilled, the electrolyte is bound. I3 has Samsung SDI, the manufacturer indicates any position.
