### ISSUE TITLE
BMW I3 More battery info

### ISSUE THREAD

**Issue by mbuhansen** [dalathegreat/Battery-Emulator#555]
Is it possible to add BMW i3 to "more battery info" menu.

### Steps to Reproduce the Problem

1.
1.
1.

### Settings

- Software version: ``
- Battery used: `BMW I3 60AH`
- Inverter communication protocol: `Kostal`
- Hardware used for Battery-Emulator: `HW_LILYGO,`
- CONTACTOR_CONTROL: `yes/
- DUAL_CAN: `yes`
- WEBSERVER: `yes/`
- MQTT: `yes/`

**Comment by dalathegreat** [comment]
Yes. Pull request now open: https://github.com/dalathegreat/Battery-Emulator/pull/556

**Comment by dalathegreat** [comment]
Closing as done!
