### ISSUE TITLE
BYD CAN Mismatch

### ISSUE THREAD

**Issue by mace-de** [dalathegreat/Battery-Emulator#562]
BYD-CAN.cpp 143-147

Based on my research, BYD Can ID 0x150 [4,5] hast to be remaining charge in 1/10 Ah and [6,7] hast to be max charge in 1/10 Ah

**Comment by dalathegreat** [comment]
I think you might be right, looks like both 0x110 and 0x150 has the same content in bytes4-7, which does seem a bit odd:

![image](https://github.com/user-attachments/assets/b7f74ab2-2094-47ae-b748-c76388e980c1)

**Comment by dalathegreat** [comment]
Attempted fix is now available here in PR https://github.com/dalathegreat/Battery-Emulator/pull/568

**Comment by dalathegreat** [comment]
Fix verified working! Closing this as completed
