### ISSUE TITLE
Double Battery Automatic Contactor Support GPIO

### ISSUE THREAD

**Issue by malcolmputer** [dalathegreat/Battery-Emulator#572]
### Expected Behavior

It would be great for double battery support to also support automatic contactor support utilizing GPIO, something like this: 

// Contactor handling
#define POSITIVE_CONTACTOR_PIN 32
#define NEGATIVE_CONTACTOR_PIN 33
#define PRECHARGE_PIN 25

#define 2ND_POSITIVE_CONTACTOR_PIN 13
#define 2ND_NEGATIVE_CONTACTOR_PIN 16
#define 2ND_PRECHARGE_PIN 18

### Actual Behavior

Currently this has to be done manually, or utilizing a battery that supports contactor control over CAN, since the 3lb board that's in development supports multiple relays, it makes sense to support this.

**Comment by dalathegreat** [comment]
PR for this is UP :raised_hands: https://github.com/dalathegreat/Battery-Emulator/pull/619

**Comment by dalathegreat** [comment]
Closed as completed! Target for 7.8.0 release!
