### ISSUE TITLE
Bmw i3 Battery has always PRECHARGE_FAILURE event with well working battery.

### ISSUE THREAD

**Issue by ababians** [dalathegreat/Battery-Emulator#574]
### Expected Behavior. The Precharge_Failure event must not happen if capacitor is seated on high voltage output. I use 7,6dev compile

 If battery is working fine with capacitor this event must not happen

### Steps to Reproduce the Problem

1. This happen after OTA update with 7,6 dev and when restarting the battery.
1.
1.

### Settings

- Software version: ``7,6 dev
- Battery used: ``BMW i3 60Ah
- Inverter communication protocol: ``Modbus
- Hardware used for Battery-Emulator: `HW_LILYGO, 
- CONTACTOR_CONTROL: `yes
- DUAL_CAN: `no`
- WEBSERVER: `yes
- MQTT: `no`

**Comment by dalathegreat** [comment]
Fix is implemented in https://github.com/dalathegreat/Battery-Emulator/pull/588
