### ISSUE TITLE
BatEmu controlled contactors fail to open correctly on Fault condition

### ISSUE THREAD

**Issue by wjcloudy** [dalathegreat/Battery-Emulator#581]
### Expected Behavior

- When using contactors controlled by battery emulator directly.
- When fault state is logged, ideally inverter should be sent zero current request and then ALL contactors should open.
- An event for contactors opened should be logged
- The web interface should show contactors open

### Actual Behavior

- On fault state, all contactors open and then precharge contactor re-engages
- No event for contactors opened is logged
- The web interface still shows contactors closed

### Steps to Reproduce the Problem

Generate ERROR level event during operation, wait till fault ticks are exceeded.

### Debug/Stepthrough

- SHUTDOWN_REQUESTED is set correctly on fault ticks exceed

- The below then causes the status to go immediately to disconnected - skipping the shutdown_requested contactor open routine. Unlike the shutdown_requested case, the DISCONNECTED contactor open case also has no event logging or state update (not sure why this is - I guess this state is the idling off position to avoid multiple events being logged)
 ```
if (contactorStatus == SHUTDOWN_REQUESTED && !datalayer.system.settings.equipment_stop_active) {
    contactorStatus = DISCONNECTED;
  }
```
- The below then causes it to go straight into PRECHARGE state
```
if (datalayer.system.status.battery_allows_contactor_closing &&
        datalayer.system.status.inverter_allows_contactor_closing) {
      contactorStatus = PRECHARGE;
    }
```
- When the loop runs again, the same logic happens over and over forced contactors to be stuck in PRECHARGE

![image](https://github.com/user-attachments/assets/a1edf797-76e5-44a1-9249-f8b92e2a3d14)

### Settings

- Software version: `7.5`
- Battery used: `iiX`
- Inverter communication protocol: `CAN`
- Hardware used for Battery-Emulator: `HW_LILYGO`
- CONTACTOR_CONTROL: `yes`
- DUAL_CAN: `yes`
- WEBSERVER: `yes`
- MQTT: `yes`

**Comment by dalathegreat** [comment]
Thanks for the report. Fix is implemented in PR https://github.com/dalathegreat/Battery-Emulator/pull/584 , which is now merged to main!
