### ISSUE TITLE
BYD Atto 3 Battery issue

### ISSUE THREAD

**Issue by Yousef9111** [dalathegreat/Battery-Emulator#590]
BYD Atto 3 Battery issue

### Actual Behavior

we use your emulator on BYD Atto 3 Battery we found that the real SOS is stuck on 94.90 or 77.50 and keep change from this tow SOC value even if i keep discharge the battery the value keep the same.
we test that on other battery (BYD atto 3 ) and we have the same value 
so if you have a solution for that to use it

thanks,

### Steps to Reproduce the Problem

1.
1.
1.

### Settings

- Software version:7.5.0 ``
- Battery used:BYD Atto 3 ``
- Inverter communication protocol: PYLON_CAN and the inverter is sofar hyd 20k ``
- Hardware used for Battery-Emulator: `HW_LILYGO`
- CONTACTOR_CONTROL: `no`
- DUAL_CAN: `yes/no`
- WEBSERVE
![Screenshot_20241101_150829_Chrome](https://github.com/user-attachments/assets/bb707955-ec7b-481b-a23d-e4d5c6fc41c0)
![Screenshot_20241101_150836_Chrome](https://github.com/user-attachments/assets/bfeb647b-1083-48e9-a7e5-7d2c865f4a87)
R: `yes/no`
- MQTT: `yes/no`

**Comment by dalathegreat** [comment]
Hi, This is normal behaviour, we **estimate** SOC% based on the battery pack voltage. This is the lookup table used:

![image](https://github.com/user-attachments/assets/ef20284f-be6f-4ebc-bd87-7eeee1a2c01d)

When load is applied, voltage sags and the SOC% reading jumps. 

The reason we estimate SOC% can be seen from the Wiki: https://github.com/dalathegreat/Battery-Emulator/wiki/BYD-Atto-3-battery

Long term, we will release a new version where you can switch to using actual battery SOC%, if your battery is not crashed and locked.
