### ISSUE TITLE
Supporting GoodWeA-ES Series

### ISSUE THREAD

**Issue by gegere** [dalathegreat/Battery-Emulator#599]
Greetings I will be connecting a GoodWe 9600A-ES to a Tesla Model 3. Reviewing the supported invertor list I see GoodWe Invertors are supported.

If not I would LOVE to support and troubleshoot.

**Comment by dalathegreat** [comment]
Should work just fine, BYD is on the [approved list](https://www.invertersupply.com/media/data/GW_Approved%20Battery%20Options%20Statement-EN.pdf) for this inverter!

**Comment by gegere** [comment]
This all works!

[more info](https://github.com/dalathegreat/Battery-Emulator/issues/620)
