### ISSUE TITLE
HYUNDAI 39.2KWH BATTERY PACK HV RELAY NOT TURNING ON

### ISSUE THREAD

**Issue by anufahim** [dalathegreat/Battery-Emulator#610]
### Steps to Reproduce the Problem

1.
1.
1.

### Settings

- Software version: ``
- Battery used: ``
- Inverter communication protocol: ``
- Hardware used for Battery-Emulator: `HW_LILYGO, HW_STARK, Custom`
- CONTACTOR_CONTROL: `yes/no`
- DUAL_CAN: `yes/no`
- WEBSERVER: `yes/no`
- MQTT: `yes/no`

**Comment by dalathegreat** [comment]
What Hyundai [part number](https://github.com/dalathegreat/Battery-Emulator/wiki/Kia-Niro---Hyundai-Kona-64kWh-battery#part-numbers-for-batteries) do you have?
