### ISSUE TITLE
BYD-CAN.cpp CAN values are decoded as little endian but should be big endian

### ISSUE THREAD

**Issue by jsphuebner** [dalathegreat/Battery-Emulator#612]
https://github.com/dalathegreat/Battery-Emulator/blob/0b966655479860f87d70e3e210dc7240639d7824/Software/src/inverter/BYD-CAN.cpp#L180

Values are decoded as LE but are BE

Those are boring values (just what you sent above) so probably no one ever used them

**Comment by dalathegreat** [comment]
Thanks @jsphuebner , fix is up in PR https://github.com/dalathegreat/Battery-Emulator/pull/613
