### ISSUE TITLE
BMW i3 more info display value switched.

### ISSUE THREAD

**Issue by mbuhansen** [dalathegreat/Battery-Emulator#633]
### Expected Behavior

In bmw i3 more info display dash soc and raw soc is switch around. display soc has to be highst value.
when bateery raw soc is 81% dispaly soc has to be 100%

In the last picture youyr can se it is switch around, it is in BMW I3.cpp

### Steps to Reproduce the Problem

1.
1.
1.

### Settings

- Software version: ``
- Battery used: ``
- Inverter communication protocol: ``
- Hardware used for Battery-Emulator: `HW_LILYGO, HW_STARK, Custom`
- CONTACTOR_CONTROL: `yes/no`
- DUAL_CAN: `yes/no`
- WEBSERVER: `yes/no`
- MQTT: `yes/no`

![Udklip v78 more](https://github.com/user-attachments/assets/e9573a23-ddae-4e55-ad53-3c60dec4b114)
![Udklip v78](https://github.com/user-attachments/assets/0e0514a6-505f-4ad5-9be4-f33379ecfad4)
![Udklip bmw i3 file](https://github.com/user-attachments/assets/899ee51c-cfcc-44df-8be6-209cca7b9aa8)

**Comment by mbuhansen** [comment]
i have change the values in my file, and it is now show correct.

here is picture when i charge to 100%

![emulator more 100%](https://github.com/user-attachments/assets/d487c741-0f53-4ccb-9204-56b4cd0d62fd)
![emulator 100%](https://github.com/user-attachments/assets/49b65424-4669-48bd-9619-73ab3774a79b)

**Comment by dalathegreat** [comment]
Thanks for the report! Fix is up in https://github.com/dalathegreat/Battery-Emulator/pull/634 , closing this as completed!
