### ISSUE TITLE
Solax Ultra App Soc

### ISSUE THREAD

**Issue by xraftest** [dalathegreat/Battery-Emulator#650]
### Expected Behavior

Soc in solax app

### Actual Behavior

Soc didnt work in app

### Steps to Reproduce the Problem

![image](https://github.com/user-attachments/assets/9b393cbb-435b-4e3a-b193-78cd92b28455)
Sending can frames to inverter fixed the problem

**Comment by dalathegreat** [comment]
Massive thanks for this discovery @xraftest , I have opened a PR with a fix: https://github.com/dalathegreat/Battery-Emulator/pull/656
