### ISSUE TITLE
Hyundai Kona 40kWh - Battery Emulator shows too high voltage (6553V)

### ISSUE THREAD

**Issue by anufahim** [dalathegreat/Battery-Emulator#678]
### Steps to Reproduce the Problem

1.
1.
1.

### Settings

- Software version: ``7.9.2
- Battery used: ``HYUNDAI KONA 40KWH
- Inverter communication protocol: ``
- Hardware used for Battery-Emulator: `HW_LILYGO, HW_STARK, Custom`
- CONTACTOR_CONTROL: `yes/no`
- CAN_ADDON: `yes/no`
- WEBSERVER: `yes/no`
- MQTT: `yes/no`
![2](https://github.com/user-attachments/assets/151b3741-51a3-42fe-8ccb-7be72cfd5c9e)
![1](https://github.com/user-attachments/assets/70024022-6ddd-4764-ac04-f2c9174d38d2)

**Comment by dalathegreat** [comment]
Sorry your battery might have internal issues, see the troubleshooting section: https://github.com/dalathegreat/Battery-Emulator/wiki/Battery:-Kia-Niro---Hyundai-Kona-64-kWh#troubleshooting

**Comment by dalathegreat** [comment]
@anufahim Were you able to find the problem with the battery?
