### ISSUE TITLE
Renault ZOE Gen1 add missing parameters

### ISSUE THREAD

**Issue by piitsi** [dalathegreat/Battery-Emulator#688]
### Expected Behavior

Add these missing values:

- Find max discharge and max charge values (for now hardcoded to 5kW)
- Fix the missing cell96 issue (Only cells 1-95 is shown)
- Find current sensor value (OVMS code reads this from inverter, which we dont have)
- Figure out why SOH% is not read (low prio)

I hope all of these (cell96 issues not sure?)  can fixed using CAN logs sent in Discord and the CAN Matrix table

**Comment by dalathegreat** [comment]
Good timing on this bugreport. Pull request is UP https://github.com/dalathegreat/Battery-Emulator/pull/689
