### ISSUE TITLE
Emulate other batteries?

### ISSUE THREAD

**Issue by ADtinkerer** [dalathegreat/Battery-Emulator#75]
What would be required to emulate a  BYD H or HVL batteries? I'd like to be able to use this with a SMA SBS6.0-US-10 inverter and SBS-ABU-200-US-10 / BUUM3-US-10 whole-home transfer switch in Canada. SMA details are here on approved equipment: https://files.sma.de/assets/275666.pdf. BYD documentation here: https://www.bydbatterybox.com/downloads#

**Comment by SIFI1971** [comment]
I can get my  hands on a mustang mach e 98KWh battery, and i have a peak canbus to usb converter. Like to give it a try @dalathegreat  ?

**Comment by dalathegreat** [comment]
Closing this issue as completed, SMA CAN emulation is in the code, testers wanted @ADtinkerer !
