### ISSUE TITLE
CAN-FD support

### ISSUE THREAD

**Issue by cgalpin** [dalathegreat/Battery-Emulator#99]
I just wanted to throw this out there since I think the battery I want to add support for (ioniq 5) uses CAN-FD messages. I am still trying to get a working setup for this myself, but the hardware will need to support CAN-FD as well as the software.

thanks,
charles

**Comment by dalathegreat** [comment]
Could be thought about for the dedicated hardware, @StarkJohan ?

**Comment by StarkJohan** [comment]
As far as I understand it the ESP32, even the newer RISC versions, does not comply with CAN-FD. One solution is the MCP251863. I have a couple of them here and I intend trying them out in the coming months. I think there's work being done on a compatible driver but I haven't really looked into the details yet. CAN-FD  should be doable as long as the driver becomes available.

**Comment by mnowa** [comment]
> I just wanted to throw this out there since I think the battery I want to add support for (ioniq 5) uses CAN-FD messages. I am still trying to get a working setup for this myself, but the hardware will need to support CAN-FD as well as the software.
> 
> thanks, charles
@cgalpin I also would like to add support for Ioniq 5 / ev6 battery. The CAN traces from https://www.csselectronics.com/pages/kia-ev6-can-bus-data-uds-dbc#ev-data-pack makes me think that support can be achieved with small modification of the code from the [kona-64_v2 branch](https://github.com/LevinSwe/BYD-Battery-Emulator-For-Gen24/tree/kona-64_v2). I'm still not 100% sure that is is CAN FD however I did not managed to establish can communication with Ioniq 5 / ev6 battery BMS yet. I tried with lillygo and kona-64_v2 code  (with small adjustments made for 77,4kWh battery ). I also tried sending CAN frames using waveshare USB to CAN FD adapter but without success so far. Like already noticed on the [Hyundai IoniQ 2020 HV battery pack na openinverter forum](https://openinverter.org/forum/viewtopic.php?t=2584&start=25) the 77,4kWh batter is not the same as kona 64kWh and "does not want to us"  :( 
Let's join force in the work on ev6/Ioniq 5 battery support.

Regards,
Marek

**Comment by mnowa** [comment]
@StarkJohan & @dalathegreat I searched for ESP32 board supporting CAN-FD but I did not found many. The most mature project/library was https://github.com/collin80/esp32_can written originally for EVTV ESP32-Due board. The board uses MCP2562FD (High-speed CAN FD Transceiver with Standby Mode and VIO Pin) and MCP2517FD/MCP2518FD (External CAN FD Controller with SPI Interface) and is rather expensive approx. 140 USD) but the library can be used for other esp32 board that contains MCP2562FD and MCP2517F/8D components.

**Comment by cgalpin** [comment]
@mnowa  I'd. love to collaborate on this. I will reach out to you when i get back from Holiday next week, but I think you have summed it up nicely - we are both stuck at trying to communicate with the battery, and are unsure if it's CAN-FD or something else (however at this point I am fairly certain it's CAN-FD, and that long term CAN-FD hardware support for the battery emulator is needed anyway to support future batteries).

I was not aware of the DBC file made by CSS electronics, thanks! Their work was done in the car, but this gives me confidence we can figure this out, and their results seem to confirm that the messages are not that different from the Kona. I have downloaded the data pack, and will try see if i can identify messages that can be used to trigger the BCM to send messages.

The lilygo does not support CAN-FD afaik (but i did get one). I actually have the CANDue board, and collins excellent SavvyCAN software, but the software support is limited for CAN-FD and I can't even enable it for the way I am using it (but I am looking into how I might be able to). I have another CANDue board which needs the CAN tranceivers replaced - if you are interested in trying to repair it, I'd be happy to send it to you. It is a bit expensive (its a general purpose board), but I am guessing the battery emulator software could run on it no problem.

I have ordered a canable, which has CAN-FD support and uses software called Cangaroo which also support CAN-FD so thats my next step to trying to get communication with the battery going. I think once I can see message we might have to send a message to get the BCM to send out messages with SoC etc as well.

charles

**Comment by mnowa** [comment]
@cgalpin Small update regarding the can protocol version used by 77,4kWh battery. I managed to find out the right can configuration for the 77,4kWh battery.  It uses ISO CAN-FD, standard type of frames with  BRS(Bit Rate Switching AKA acceleration), 500kbit/s bit-rate for arbitration and 2 Mbit/s for data. I managed to trigger the BMS using frame with ID=0x7E4 and 03 22 01 01 00 00 00 00 hex payload. BMS sent back the  frame having ID=0x7EC and 10 3E 62 01 01 EF FB E7 payload. Next I sent ACK frame (ID=0x7E4  and 30 00 00 00 00 00 00 00 payload) and got 8 subsequent frames with IDs equal to 0x7EC and first bytes 0x21 to 0x28 respectively. 
So, the communication quite  similar to MF4 logs shared by https://www.csselectronics.com/pages/kia-ev6-can-bus-data-uds-dbc#ev-data-pack and for decoding it code from [kona-64_v2 branch](https://github.com/LevinSwe/BYD-Battery-Emulator-For-Gen24/tree/kona-64_v2) shall be used as base.
For testing I used [waveshare usb can fd](https://www.waveshare.com/usb-can-fd.htm)  and of course the target hardware should be based on some esp32 with something capable to handle can-fd.
I'm bit limited with development options using waveshare usb can fd  and I'm looking for some ready to use board (maybe [mcp251863 click board  ](https://www.mikroe.com/mcp251863-click) that would allow me to integrate it with esp32.  Any recommendations would be appreciated.

**Comment by cgalpin** [comment]
@mnowa this is fantastic news!  I hope the 72.6kWh is the same.

I will not be able to try until next week, but will see if I can replicate using the canable and cangaroo as a start. I do not have better answers on hardware - I will likely try use my CANDue once I can confirm it works with canable.

**Comment by cgalpin** [comment]
First Marek/@mnowa I don't know how to reach out to you directly - are you maciek16c on the openinverter.org forums? I am the ever creative cgalpin there too.

My canable arrived and I am able to see CAN traffic on the bus using cangaroo which makes me very happy since i have been unable to get any messages until now (but the dbc file from CSS electronics does not work so I will need to look into that).

I was also able to trigger the BMS using frame with ID=0x7E4 and 03 22 01 01 00 00 00 00 hex payload. The BMS sent back the frame having ID=0x7EC and 10 3E 62 01 01 EF FB E7 payload like you.

However it is not responding to the follow up ACK frame (ID=0x7E4 and 30 00 00 00 00 00 00 00 payload) for me. Does this have to come in quick succession? I am slow at typing out the payload :) 

It is also cold out in my garage so I am going to setup a raspberry pi out there and work remotely from inside to make this easier - hopefully this weekend since I need to order a long ethernet cable.  

As far as hardware goes, I was wondering if the canable can be wired to something like a ESP32 Devkit V1 to use the CAN-FD  as a serial device? That would a cheap combo, even if just for development.

charles

**Comment by cgalpin** [comment]
@mnowa I guess you are not maciek16c on the openinverter.org forums :)  @maciek16c is on github and just added some [CAN-FD support](https://github.com/collin80/SavvyCAN/pull/702) to SavvyCAN Lawicel connections which allows it to start showing data for me from a Canable 2! 

I have played around a bit using the SavvyCAN javascript interface and can get the frames with ID=0x7EC and first bytes 0x21 through 0x28 that way. I think I will work a little more this way before doing the same in a sketch on my esp32 candue. I am working off of the [kona-64_v2](https://github.com/LevinSwe/BYD-Battery-Emulator-For-Gen24/blob/kona-64_v2/Software/KIA-HYUNDAI-64-BATTERY.cpp) branch you suggested, but have yet to send any messages other than the first two (where poll_data_pid == 1). The highest message ID I currently get is 0x3F5, so hoping once I start sending more messages I'll start getting the rest.

**Comment by mnowa** [comment]
> @mnowa I guess you are not maciek16c on the openinverter.org forums :) @maciek16c is on github and just added some [CAN-FD support](https://github.com/collin80/SavvyCAN/pull/702) to SavvyCAN Lawicel connections which allows it to start showing data for me from a Canable 2!

I used the [MarekN](https://openinverter.org/forum/memberlist.php?mode=viewprofile&u=5878&sid=c44f1e120aefbb58b3e361868ed6b1cc) nickname on openinverter.org forum.

> As far as hardware goes, I was wondering if the canable can be wired to something like a ESP32 Devkit V1 to use the CAN-FD as a serial device? That would a cheap combo, even if just for development.

Not sure about canable since it uses usb, but some module that uses SPI (e.g. like [waveshare 2-Channel CAN HAT](https://www.waveshare.com/2-ch-can-hat.htm) or [MCP251863 click board](https://www.mikroe.com/mcp251863-click) could be and option but I'm not a specialist in hardware)


As for the CAN interaction and your question:

> However it is not responding to the follow up ACK frame (ID=0x7E4 and 30 00 00 00 00 00 00 00 payload) for me. Does this have to come in quick succession? I am slow at typing out the payload :)

I think the ACK need to be send ASAP otherwise it will be ignored...

**Comment by maciek16c** [comment]
These frames are UDS (obd2) messages and are using ISO-TP protocol. Frames should be automatically assembled and flow control / ack added by ISO-TP library

**Comment by cgalpin** [comment]
Thanks so much @maciek16c. It sounds like UDS is what is needed here.

We should definitely collaborate with @mnowa on this, although you seem to be well ahead of me on this :D

**Comment by Camelrider79** [comment]
Canable V2 with Cangaroo supports CAN FD fine, attached the Battpack CANDATA from KIA EV6 and Ionic 5 (77,4Kw Bat)
[test.txt](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/files/13728360/test.txt)

**Comment by Camelrider79** [comment]
What about this board WeAct STM32G431CBU6 STM32G431 STM32G4 STM32 Core Board Demo Board, is it possible to use that board in combination with Lillygo? STM32G431 Supports canfd. (its also the main chip on canable)

**Comment by cgalpin** [comment]
Yes I have been using a Canable V2 to look at mine, but using SavvyCAN. Cangaroo can't read the dbc files I have and has less functionality than SavvyCAN

What format is this log in? SavvyCAN cannot load it. Is it the trace output from Cangaroo? 

> Canable V2 with Cangaroo supports CAN FD fine, attached the Battpack CANDATA from KIA EV6 and Ionic 5 (77,4Kw Bat) [test.txt](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/files/13728360/test.txt)

**Comment by Camelrider79** [comment]
> Yes I have been using a Canable V2 to look at mine, but using SavvyCAN. Cangaroo can't read the dbc files I have and has less functionality than SavvyCAN
> 
> What format is this log in? SavvyCAN cannot load it. Is it the trace output from Cangaroo?
> 
> > Canable V2 with Cangaroo supports CAN FD fine, attached the Battpack CANDATA from KIA EV6 and Ionic 5 (77,4Kw Bat) [test.txt](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/files/13728360/test.txt)

Its a ASC File (it was not possible to upload the asc here).

i can try to read the data with savvycan, but i can't get it to run under windows in combination with canable v2 pro.

**Comment by cgalpin** [comment]
You need the latest SavvyCAN development build, or build from source because the support waqs just recently added by @maciek16c.

I thought i replied earlier, but I changed the extension to .asc and SavvyCAN could not read it. It would be nice to be able to playback and compare

**Comment by Camelrider79** [comment]
If you could provide me with the build I would be very happy.
Then I'll have a look right away.
Which settings do I have to make for Savvy? the canable is not selectable like this

**Comment by cgalpin** [comment]
For windows 64 bit, try this - https://github.com/collin80/SavvyCAN/releases/download/continuous/SavvyCAN-Windows_x64_CIBuild.zip

From the connection window, Add New Device Connection, and just pick LAWICEL / SLCAN Serial and the options will be obvious.

**Comment by Camelrider79** [comment]
Try this to read
[Akkupack Ev6 SavvyC.csv](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/files/13757269/Akkupack.Ev6.SavvyC.csv)

**Comment by cgalpin** [comment]
Yes, I can play this back, thanks! Was this captured from a car, or just a standalone battery? I am out of time today, but will take a look at this as soon as I can.

Not sure what to say about SavvyCAN - I have not tried the latest on windows, but I can try tomorrow maybe.

**Comment by Camelrider79** [comment]
Its from Battery only, without the 5V crash signal(not connected at the moment, and also without the 12k resistor)
I have also the log from car but captured with cangaroo...

**Comment by cgalpin** [comment]
> Try this to read [Akkupack Ev6 SavvyC.csv](https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24/files/13757269/Akkupack.Ev6.SavvyC.csv)
> 
> I can access the data in real time with Cangaroo, but I can't do it with savvy.

I just tried this on windows 10 and it worked fine for me. serial speed 115200, canbus speed 500k, data speed 2M, CAN-FD checked

**Comment by kukumagi** [comment]
Hello.
Not related to the thread: where can I ask for a discord invite?

Are these previously mentioned can messages already documented somewhere?

**Comment by Camelrider79** [comment]
https://www.patreon.com/dala/membership

you can see the discord link

**Comment by kukumagi** [comment]
Should I assume that I cant send messages because the mcp2515 does not support can FD?
Currently I can get data from battery but I dont get response for 7E4 message.

**Comment by Camelrider79** [comment]
I don't know exactly what the mcp can do, I have similar problems at the moment (maybe because of the software, I don't know if savvycan uses can or canfd when replaying, im using at the moment the canable stick), so I'm waiting for my Kvaser that I ordered. Hope to be able to send back canfd signals. I have the complete M-Can and G-can log from ev6 at startup, maybe both ports need to be addressed at the same time. Come into the discord and you will see the individual steps.

**Comment by kukumagi** [comment]
After reading that can FD is not backwards compatible it means that MCP2515 is something that cannot be used for this application.
Cant access discord link without patreon membership :D.

**Comment by Camelrider79** [comment]
https://discord.gg/xUbfW2hs 
Invite is only 1week active

**Comment by dalathegreat** [comment]
CAN-FD support is being worked on;

Wiki: https://github.com/dalathegreat/Battery-Emulator/wiki/CAN%E2%80%90FD-add%E2%80%90on-chip
Branch: https://github.com/dalathegreat/Battery-Emulator/tree/feature/CAN-FD

**Comment by cgalpin** [comment]
This looks awesome!  I’ll get the add on chip and give this a try, but I still can’t find an inverter that will work with 800v in the US (single phase 240v)

**Comment by kukumagi** [comment]
CAN FD support was added with this PR: https://github.com/dalathegreat/Battery-Emulator/pull/244

**Comment by dalathegreat** [comment]
Closing this, as CAN-FD is added, and here is a quick video on how to hook up the chip: https://www.youtube.com/watch?v=uhOy7coatQQ
